(local transform)
(local rigidbody)
(local start (fun (do
	(set transform (transform-require entity))
	(transform-move transform (vec 0 0 2))
	(set rigidbody (rigidbody-require entity))
	(set character-rigidbody rigidbody)
	(sprite-load (sprite-add entity) "spritesheet.png")
	(local collider (collider-add entity))
	(collider-box collider (vec 1 1 1))
)))
(local update (fun (do
	(local movement (* delta 16))
	(if (key-pressed UP) 		(rigidbody-addspeed rigidbody (vec 0 movement 0)))
	(if (key-pressed LEFT) 	(rigidbody-addspeed rigidbody (vec (- movement) 0 0)))
	(if (key-pressed DOWN)	(rigidbody-addspeed rigidbody (vec 0 (- movement) 0)))
	(if (key-pressed RIGHT) (rigidbody-addspeed rigidbody (vec movement 0 0)))
	(if (key-pressed SPACE) (rigidbody-addspeed rigidbody (vec 0 0 movement)))
)))
