set(RMLUI_INSTALL_DIR ${CMAKE_CURRENT_SOURCE_DIR}/ext/rmlui/$<CONFIG>)
set(RMLUI_LIBRARIES
  ${RMLUI_INSTALL_DIR}/lib/RmlCore
  #${RMLUI_INSTALL_DIR}/lib/RmlDebugger
)

ExternalProject_Add(
  ext_rmlui
  GIT_REPOSITORY https://github.com/mikke89/RmlUi.git
  GIT_TAG 31e567ce88fe73c3d05b32d30b1911bda159a6bb # v4.1
  GIT_SHALLOW true
  UPDATE_COMMAND ""
  CMAKE_ARGS
    -DCMAKE_INSTALL_PREFIX=${RMLUI_INSTALL_DIR}
    -DBUILD_SHARED_LIBS=OFF
    -DNO_FONT_INTERFACE_DEFAULT=ON
    -DNO_THIRDPARTY_CONTAINERS=ON
    -DDISABLE_RTTI_AND_EXCEPTIONS=ON
)

add_module(
  rmlui
  DEPENDENCIES ext_rmlui
  INCLUDE_DIRS ${RMLUI_INSTALL_DIR}/include
  LIBRARIES ${RMLUI_LIBRARIES}
)
