(setting 'fullscreen 0)
(setting 'resolution_x 1024)
(setting 'resolution_y 768)
(setting 'resizable_window 1)
(setting 'render_collider 0)
(setting 'render_skeletal_animator 0)
(engine_clear_and_read "proxy.lasm")
