(self.shader 'fragment "shader/pointlight.frag")
(self.shader 'vertex "shader/sphere.vert")
(self.cull_mode 'front)
(self.render_pass 'light)
(self.scalar 'intensity 1)
(self.vector 'color "white")
(self.vertex_count (* 8 3 4))
