(self.shader 'fragment "shader/pointlight.frag")
(self.shader 'vertex "shader/color.vert")
(self.mesh "mesh/sphere.ls?fmt=pn")
(self.cull_mode 'front)
(self.render_pass 'light)
(self.scalar 'intensity 1)
(self.vector 'color "white")
