(self.shader 'fragment "shader/pointlight.frag")
(self.shader 'vertex "shader/sphere.vert")
(self.cull-mode 'front)
(self.render-pass 'light)
(self.scalar 'intensity 1)
(self.vector 'color "white")
(self.vertex-count (* 8 3 4))
