set(RMLUI_LIBRARIES
  lib/RmlCore
  #lib/RmlDebugger
)

add_external(
  rmlui
  CMAKE
  CONFIG_INSTALL_DIR
  GIT_REPOSITORY https://github.com/mikke89/RmlUi.git
  GIT_TAG 31e567ce88fe73c3d05b32d30b1911bda159a6bb # v4.1
  INCLUDE_DIRS include
  LIBRARIES ${RMLUI_LIBRARIES}
  CMAKE_ARGS
    -DBUILD_SHARED_LIBS=OFF
    -DNO_FONT_INTERFACE_DEFAULT=ON
    -DNO_THIRDPARTY_CONTAINERS=ON
    -DDISABLE_RTTI_AND_EXCEPTIONS=ON
)
