set(RMLUI_LIBRARIES
  lib/RmlCore
  lib/RmlDebugger
)

add_external(
  rmlui
  CMAKE
  CONFIG_INSTALL_DIR
  GIT_REPOSITORY https://github.com/mikke89/RmlUi.git
  GIT_TAG 38d63558afbac60e7c6fd16d4fa17ae9d80799b2
  INCLUDE_DIRS include
  LIBRARIES ${RMLUI_LIBRARIES}
  CMAKE_ARGS
    -DBUILD_SHARED_LIBS=OFF
    -DNO_FONT_INTERFACE_DEFAULT=ON
    -DNO_THIRDPARTY_CONTAINERS=ON
    -DDISABLE_RTTI_AND_EXCEPTIONS=ON
)
